name: cost_plan
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  #local
  drift: ^2.9.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.3

  #UI
  dropdown_button2: ^2.1.4
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  social_share: ^2.3.1
  appinio_social_share: ^0.2.0
  pull_to_refresh: ^2.0.0
  uni_links: ^0.5.1
  go_router: ^9.0.0
  scroll_to_index: ^3.0.1
  flutter_web_frame: ^0.0.3
  google_maps_flutter: ^2.2.3
  google_maps_cluster_manager: ^3.0.0+1
  keyboard_actions: ^4.1.0

  #geolocation
  geolocator: ^9.0.2

  #localization
  intl: ^0.18.0

  #state management
  flutter_bloc: ^8.0.0

  #json
  json_annotation: ^4.7.0

  #Http client
  dio: ^5.2.1+1

  #local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.15

  #logging
  logger: ^1.1.0

  #firebase
  firebase_core: ^2.2.0
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^15.0.0
  firebase_analytics: ^10.1.0
  

  #Reactive programming
  rxdart: 0.27.7
  get_it: ^7.6.0
  bloc: ^8.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  drift_dev: ^2.9.0
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  hive_generator: ^2.0.0
  custom_lint: ^0.4.0
  dartz: ^0.10.1

flutter:
  assets:
   - assets/icons/
  uses-material-design: true
flutter_intl:
  enabled: true
  main_locale: ru

