name: cost_plan
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  #UI
  dropdown_button2: ^1.9.2
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  social_share: ^2.3.1
  appinio_social_share: ^0.2.0
  pull_to_refresh: ^2.0.0
  uni_links: ^0.5.1
  go_router: ^6.0.1
  scroll_to_index: ^3.0.1
  flutter_web_frame: ^0.0.3
  google_maps_flutter: ^2.2.3
  google_maps_cluster_manager: ^3.0.0+1
  keyboard_actions: ^4.1.0

  #geolocation
  geolocator: ^9.0.2

  #localization
  intl: ^0.17.0

  #state management
  flutter_riverpod: ^2.0.2
  riverpod_annotation: ^1.0.4
  freezed_annotation: ^2.2.0

  #json
  json_annotation: ^4.7.0

  #Http client
  dio: ^4.0.6

  #local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.15

  #logging
  logger: ^1.1.0

  #firebase
  firebase_core: ^2.2.0
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^12.0.3
  firebase_analytics: ^10.1.0
  

  #Reactive programming
  rxdart: 0.27.7


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  hive_generator: ^2.0.0


flutter:
  assets:
   - assets/icons/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
        - asset: assets/fonts/Nunito-ExtraBold.ttf
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-SemiBold.ttf
  uses-material-design: true
flutter_intl:
  enabled: true
  main_locale: ru

